title: Sangsoon's blog
description: Web Developer
site_title: Sangsoon's blog

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ssoon92
blog_url: https://ssoon92.github.io
email: jason1950@naver.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 