title: Sangsoon's story
description: Web Developer
site_title: Sangsoon's story

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ssoon92
blog_url: https://ssoon92.github.io
email: jason1950@naver.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.png
person: assets/images/person.png
location: assets/images/location.png
email: assets/images/email.png
calender: assets/images/calender.png
telephone: assets/images/telephone.png
pencil: assets/images/pencil.png

# Google Analytics ID
google_analytics: 